// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Main_Bay
NumericVector Main_Bay(NumericMatrix Table, NumericVector Beta_origin, NumericVector size, Nullable<NumericVector> M_ave_ori, int S, int thres, double Mean_depth, LogicalVector debug);
RcppExport SEXP _bayNorm_Main_Bay(SEXP TableSEXP, SEXP Beta_originSEXP, SEXP sizeSEXP, SEXP M_ave_oriSEXP, SEXP SSEXP, SEXP thresSEXP, SEXP Mean_depthSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Table(TableSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Beta_origin(Beta_originSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type M_ave_ori(M_ave_oriSEXP);
    Rcpp::traits::input_parameter< int >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type thres(thresSEXP);
    Rcpp::traits::input_parameter< double >::type Mean_depth(Mean_depthSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(Main_Bay(Table, Beta_origin, size, M_ave_ori, S, thres, Mean_depth, debug));
    return rcpp_result_gen;
END_RCPP
}
// Main_mode_Bay
NumericMatrix Main_mode_Bay(NumericMatrix Table, NumericVector Beta_origin, NumericVector size, Nullable<NumericVector> M_ave_ori, int S, int thres, double Mean_depth);
RcppExport SEXP _bayNorm_Main_mode_Bay(SEXP TableSEXP, SEXP Beta_originSEXP, SEXP sizeSEXP, SEXP M_ave_oriSEXP, SEXP SSEXP, SEXP thresSEXP, SEXP Mean_depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Table(TableSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Beta_origin(Beta_originSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type M_ave_ori(M_ave_oriSEXP);
    Rcpp::traits::input_parameter< int >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type thres(thresSEXP);
    Rcpp::traits::input_parameter< double >::type Mean_depth(Mean_depthSEXP);
    rcpp_result_gen = Rcpp::wrap(Main_mode_Bay(Table, Beta_origin, size, M_ave_ori, S, thres, Mean_depth));
    return rcpp_result_gen;
END_RCPP
}
// GradientFun_2D
NumericVector GradientFun_2D(NumericVector SIZE_MU, NumericVector m_observed, NumericVector BETA);
RcppExport SEXP _bayNorm_GradientFun_2D(SEXP SIZE_MUSEXP, SEXP m_observedSEXP, SEXP BETASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type SIZE_MU(SIZE_MUSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m_observed(m_observedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type BETA(BETASEXP);
    rcpp_result_gen = Rcpp::wrap(GradientFun_2D(SIZE_MU, m_observed, BETA));
    return rcpp_result_gen;
END_RCPP
}
// MarginalF_2D
double MarginalF_2D(NumericVector SIZE_MU, NumericVector m_observed, NumericVector BETA);
RcppExport SEXP _bayNorm_MarginalF_2D(SEXP SIZE_MUSEXP, SEXP m_observedSEXP, SEXP BETASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type SIZE_MU(SIZE_MUSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m_observed(m_observedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type BETA(BETASEXP);
    rcpp_result_gen = Rcpp::wrap(MarginalF_2D(SIZE_MU, m_observed, BETA));
    return rcpp_result_gen;
END_RCPP
}
// GradientFun_1D
double GradientFun_1D(double SIZE, double MU, NumericVector m_observed, NumericVector BETA);
RcppExport SEXP _bayNorm_GradientFun_1D(SEXP SIZESEXP, SEXP MUSEXP, SEXP m_observedSEXP, SEXP BETASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type SIZE(SIZESEXP);
    Rcpp::traits::input_parameter< double >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m_observed(m_observedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type BETA(BETASEXP);
    rcpp_result_gen = Rcpp::wrap(GradientFun_1D(SIZE, MU, m_observed, BETA));
    return rcpp_result_gen;
END_RCPP
}
// MarginalF_1D
double MarginalF_1D(double SIZE, double MU, NumericVector m_observed, NumericVector BETA);
RcppExport SEXP _bayNorm_MarginalF_1D(SEXP SIZESEXP, SEXP MUSEXP, SEXP m_observedSEXP, SEXP BETASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type SIZE(SIZESEXP);
    Rcpp::traits::input_parameter< double >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m_observed(m_observedSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type BETA(BETASEXP);
    rcpp_result_gen = Rcpp::wrap(MarginalF_1D(SIZE, MU, m_observed, BETA));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bayNorm_Main_Bay", (DL_FUNC) &_bayNorm_Main_Bay, 8},
    {"_bayNorm_Main_mode_Bay", (DL_FUNC) &_bayNorm_Main_mode_Bay, 7},
    {"_bayNorm_GradientFun_2D", (DL_FUNC) &_bayNorm_GradientFun_2D, 3},
    {"_bayNorm_MarginalF_2D", (DL_FUNC) &_bayNorm_MarginalF_2D, 3},
    {"_bayNorm_GradientFun_1D", (DL_FUNC) &_bayNorm_GradientFun_1D, 4},
    {"_bayNorm_MarginalF_1D", (DL_FUNC) &_bayNorm_MarginalF_1D, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_bayNorm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
